### PR TITLE
Modified try-it ui for new design.

### PR DESCRIPTION
**Pull request by hemikak**
screen shot 2017-11-08 at 12 09 56 pm
screen shot 2017-11-08 at 12 09 37 pm

### CODE REVIEW

**Comment by srsharon** [comment]
@hemikak this looks good, just a small suggestion shall we change the green in the response to #2ecc71 color to match the flat color theme.. 
image

**Comment by hemikak** [comment]
@srsharon , I presume you are talking about the text colors for 'Request URL', 'Response code', etc ?

sure can change, 
These are the colors we have, 
https://github.com/hemikak/composer/blob/e3b3f6a06c4f9388c35544bf954c2926a99adddb/modules/web/src/plugins/try-it/views/http-client.scss#L299-L320

Let me know what else needs to be changed, I picked them up from a material color site.

**Comment by srsharon** [comment]
@hemikak will you be able to follow https://flatuicolors.com/ this has 10 basic colors and its color shades.

**Comment by hemikak** [comment]
screen shot 2017-11-08 at 2 53 09 pm
screen shot 2017-11-08 at 2 53 01 pm
screen shot 2017-11-08 at 2 52 50 pm

**Pull request merged**
