### PR TITLE
Fix duplicate folder open popup for pacakged samples and make go-to-source reveal hidden lines

### PR DESCRIPTION
**Pull request by kaviththiranga**
Fixes https://github.com/ballerinalang/composer/issues/4908

### CODE REVIEW

**Comment by hemikak** [comment]
@kaviththiranga , The purpose of 'isFile' was to state that it is a packaged sample(not a single file) and the samples on the welcome would have a different view(stacked). Wouldnt this change the view of the samples in the welcome page. ?

**Comment by kaviththiranga** [comment]
@hemikak 

Seems that same property has been used to file a folder open for the parent folder. shall we introduce another property then? I didn't notice the changes to view.

**Comment by hemikak** [comment]
@kaviththiranga , yes, lets change the properties. +1

**Comment by kaviththiranga** [comment]
@hemikak updated, plz review.

**Pull request merged**
